pypet/views/gallery.py
from flask import Blueprint, render_template

bp = Blueprint('gallery', __name__, url_prefix='/gallery')

@bp.route('/photo')
def photo():
    return render_template('gallery/photo.html')

pypet/views/hosp.py
from flask import Blueprint, render_template

bp = Blueprint('hospmap', __name__, url_prefix='/hospmap')

@bp.route('/hosp')
def hosp():
    return render_template('hospmap/hosp.html')

pypet/views/upchat.py
from flask import Blueprint, render_template
from flask_socketio import emit
from pypet import socketio

bp = Blueprint('chating', __name__, url_prefix='/chating')

@bp.route('/chat')
def chat():
    return render_template('chating/chat.html')

@socketio.on('message', namespace='/chating')
def handle_message(data):
    print('received message: ' + str(data))
    emit('message', data, broadcast=True, namespace='/chating')

pypet/views/upload.py
from flask import Blueprint, render_template


bp = Blueprint('upload', __name__, url_prefix='/upload')

@bp.route('/video')
def video():
    return render_template('upload/video.html')

pypet/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}" />
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='home.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='photo.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='video.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='container-box.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='chatform.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='font/font.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='location.css')}}">
    <link rel="stylesheet" href="{{ url_for('static', filename='login.css')}}">
    <link rel="stylesheet" href="{{ url_for('static', filename='scroll.css')}}">
    <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
    <title>PetGallery</title>
</head>
<body class='bg'>
    {% include 'navbar.html' %}
    {% if g.user %}
    {% endif %}
   
    <!-- 기본 템플릿 안에 삽입될 내용 Start -->
    {% block content %}
    {% endblock %}
    <!-- 기본 템플릿 안에 삽입될 내용 End -->

    <!--location-->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDXogd-c9vnx6zK26ZaGn5JCMv-yse98C4&callback=initMap" async defer></script>
    <script src="{{ url_for('static', filename='location.js') }}" ></script>

    <!-- 소켓-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.0/socket.io.js"></script>
    <script src="{{ url_for('static', filename='socket.js') }}"></script>

    <!-- Popper.js -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.bundle.min.js"></script>
    <script src="{{ url_for('static', filename='bootstrap.min.js') }}"></script>
    
    {% block script %}
    <!--JS -->
    <script src="{{ url_for('static', filename='nav.js') }}"></script>
    <script src="{{ url_for('static', filename='time_script.js') }}"></script>
    <script src="{{ url_for('static', filename='photo.js') }}"></script>
    <script src="{{ url_for('static', filename='video.js') }}"></script>



    {% endblock %}
    <!-- 자바스크립트 End -->
</body>
</html>

pypet/templates/form_errors.html
<!-- 필드오류 -->
{% if form.errors %}
<div class="alert alert-danger" role="alert">
    {% for field, errors in form.errors.items() %}
    <strong>{{ form[field].label }}</strong>
    <ul>
        {% for error in errors %}
        <li>{{ error }}</li>
        {% endfor %}
    </ul>
    {% endfor %}
</div>
{% endif %}
<!-- flash 오류 -->
{% for message in get_flashed_messages() %}
<div class="alert alert-danger" role="alert">
    {{ message }}
</div>
{% endfor %}

pypet/templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light border-bottom">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{ url_for('main.home') }}"><img src="{{ url_for('static', filename='images/Dog_log.png') }}" alt="Logo" width="70" height="70" /></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item menu">
          <a class="nav-link dropdown-toggle" href="{{ url_for('main.home') }}">Explore</a>
          <ul class="dropdown-menu hide">
            <li>
              <a class="dropdown-item" href="{{ url_for('gallery.photo') }}">Upload a picture</a>
            </li>
            <li>
              <a class="dropdown-item" href="{{ url_for('upload.video') }}">Cooking video</a>
            </li>
            <li>
              <a class="dropdown-item" href="{{ url_for('main.index') }}">Board</a>
            </li>
            <li>
              <a class="dropdown-item" href="{{ url_for('hospmap.hosp') }}">Animal hospital location</a>
            </li>
            <li>
              <a class="dropdown-item" href="{{ url_for('chating.chat') }}">chating</a>
            </li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('gallery.photo') }}">Gallery</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('upload.video') }}">Video</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('main.index') }}">Board</a>
        </li>
      </ul>

        <!-- 메인 로그인화면 -->
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          {% if g.user %}
          <li class="nav-item">
              <a class="nav-link" href="{{ url_for('auth.profile') }}">Information</a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
              <a class="nav-link" href="{{ url_for('auth.signup') }}">Sign up</a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
          </li>
          {% endif %}
      </ul> 
      
        </div>
    </div>
    </nav>